sudo: required
dist: trusty
language: cpp
compiler:
    - gcc
    - clang
os:
    - linux
    - osx
notifications:
    email:
        recipients:
            - dilawar.s.rajput@gmail.com
            - bhalla@ncbs.res.in
            - hrani@ncbs.res.in
        on_success: change
        on_failure: always

env:
    - CTEST_MODEL=Nightly
cache: apt

matrix:
    allow_failures:
        compiler:
            - clang
        os:
            - osx
    include:
        - os : linux
          dist : trust 
          sudo : required 
        - os : osx
          osx_image : xcode8.1

before_script:
    - sudo apt-get install -qq libxml2-dev libbz2-dev
    - sudo apt-get install -qq libhdf5-serial-dev
    - sudo apt-get install -qq make cmake
    - sudo apt-get install -qq  python-numpy python-matplotlib python-networkx
    - sudo apt-get install -qq  python3-numpy python3-matplotlib python3-dev
    - sudo apt-get install -qq libboost-all-dev
    - sudo apt-get install -qq libgsl0-dev
    - sudo apt-get install -qq python-pip python3-pip
    - sudo apt-get install -qq libgraphviz-dev
    - echo "OsX related"
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gsl hdf ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libsbml ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install homebrew/python/numpy ; fi

install:
    - echo "nothing to do here"

script:
    - # checking if any python3 incompatible file is in the source tree.
    - python2 -m compileall -q .
    - python3 -m compileall -q .
    - # Then run the old make scripts
    - make 
    - ## CMAKE based flow
    - mkdir -p _GSL_BUILD && cd _GSL_BUILD && cmake -DDEBUG=ON -DPYTHON_EXECUTABLE=/usr/bin/python ..
    - make && ctest --output-on-failure
    - cd .. # Now with boost.
    - mkdir -p _BOOST_BUILD && cd _BOOST_BUILD && cmake -DWITH_BOOST=ON -DDEBUG=ON -DPYTHON_EXECUTABLE=/usr/bin/python ..
    - make && ctest --output-on-failure
    - cd .. 
    - echo "Python3 support. Removed python2-networkx and install python3"
    - sudo apt-get remove -qq python-networkx
    - sudo apt-get install -qq python3-networkx
    - mkdir -p _GSL_BUILD2 && cd _GSL_BUILD2 && cmake -DDEBUG=ON -DPYTHON_EXECUTABLE=/usr/bin/python3 ..
    - make && ctest --output-on-failure
    - cd .. # Now with BOOST and python3
    - mkdir -p _BOOST_BUILD2 && cd _BOOST_BUILD2 && cmake -DWITH_BOOST=ON -DDEBUG=ON -DPYTHON_EXECUTABLE=/usr/bin/python3 ..
    - make && ctest --output-on-failure
    - cd ..
    - echo "All done. Phew"
