language: cpp
compiler:
    - gcc
    - clang
os:
    #- linux
    - osx
notifications:
    email:
        recipients:
            - dilawar.s.rajput@gmail.com
            - bhalla@ncbs.res.in
            - hrani@ncbs.res.in
        on_success: change
        on_failure: always

env:
    - CTEST_MODEL=Nightly
cache: apt

matrix:
    allow_failures:
        os: osx
    include:
        - os : linux
          dist : trusty
          sudo : required 
        - os : osx
          osx_image : xcode8.1

before_script:
    - echo "OSX related"
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          brew update;
          brew install cmake;
          brew install homebrew/science/gsl homebrew/science/hdf5;
          brew install homebrew/science/libsbml;
          brew install homebrew/python/numpy;
          brew install python3;
          brew install boost;
      else
          sudo apt-get install -qq libxml2-dev libbz2-dev;
          sudo apt-get install -qq libhdf5-serial-dev;
          sudo apt-get install -qq make cmake;
          sudo apt-get install -qq  python-numpy python-matplotlib python-networkx;
          sudo apt-get install -qq  python3-numpy python3-matplotlib python3-dev;
          sudo apt-get install -qq libboost-all-dev;
          sudo apt-get install -qq libgsl0-dev;
          sudo apt-get install -qq python-pip python3-pip;
          sudo apt-get install -qq libgraphviz-dev;
      fi

install:
    - echo "nothing to do here"

script:
    - # checking if any python3 incompatible file is in the source tree.
    - python2 -m compileall -q .
    - python3 -m compileall -q .
    - # Then run the old make scripts
    - make 
    - ## CMAKE based flow
    - mkdir -p _GSL_BUILD && cd _GSL_BUILD && cmake -DDEBUG=ON -DPYTHON_EXECUTABLE=`which python` ..
    - make && ctest --output-on-failure
    - cd .. # Now with boost.
    - mkdir -p _BOOST_BUILD && cd _BOOST_BUILD && cmake -DWITH_BOOST=ON -DDEBUG=ON -DPYTHON_EXECUTABLE=`which python` ..
    - make && ctest --output-on-failure
    - cd .. 
    - echo "Python3 support. Removed python2-networkx and install python3"
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "nothing"; else sudo apt-get remove -qq python-networkx fi;
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "nothing"; else sudo apt-get install -qq python3-networkx fi;
    - mkdir -p _GSL_BUILD2 && cd _GSL_BUILD2 && cmake -DDEBUG=ON -DPYTHON_EXECUTABLE=`which python3` ..
    - make && ctest --output-on-failure
    - cd .. # Now with BOOST and python3
    - mkdir -p _BOOST_BUILD2 && cd _BOOST_BUILD2 && cmake -DWITH_BOOST=ON -DDEBUG=ON -DPYTHON_EXECUTABLE=`which python3` ..
    - make && ctest --output-on-failure
